name = "isspiss-backend"
main = "src/index.ts"
compatibility_date = "2024-12-18"

[durable_objects]
bindings = [
  { name = "PISS_MONITOR", class_name = "PissMonitor" }
]

[[migrations]]
tag = "v1"
new_classes = ["PissMonitor"]
